# conda env create --file environment.yml
# mamba env create --file environment.yml
# micromamba env create --file environment.yml
name: apds_energy
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - kaggle
  - python-dotenv
  - black
  - invoke
  - jupyter
  - jupyterlab
  - matplotlib
  - nbdime
  - numpy
  - pandas
  - pip
  - plotly
  - pyjanitor
  - pyprojroot
  - python=3.12
  - seaborn
  - statsmodels